/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type GetV1ChannelPreferredLanguageCodeParams = {
/**
 * Language code
 */
lang: string;
/**
 * Preferred language code
 */
preferredLang: string;
};
