/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type PgtypeInfinityModifier = typeof PgtypeInfinityModifier[keyof typeof PgtypeInfinityModifier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PgtypeInfinityModifier = {
  Infinity: 1,
  Finite: 0,
  NegativeInfinity: -1,
} as const;
