/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { PgtypeInfinityModifier } from './pgtypeInfinityModifier';

export interface PgtypeTimestamptz {
  infinityModifier?: PgtypeInfinityModifier;
  time?: string;
  valid?: boolean;
}
