/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { StarrynightComServerInternalChannelDomainValueobjectHostType } from './starrynightComServerInternalChannelDomainValueobjectHostType';

export interface StarrynightComServerInternalChannelDomainEntityHostInterface {
  type?: StarrynightComServerInternalChannelDomainValueobjectHostType;
}
