/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { StarrynightComServerInternalChannelDomainEntityHostInterface } from './starrynightComServerInternalChannelDomainEntityHostInterface';
import type { StarrynightComServerInternalSharedValueobjectLanguageCode } from './starrynightComServerInternalSharedValueobjectLanguageCode';
import type { StarrynightComServerInternalChannelDomainEntitySpeechInterface } from './starrynightComServerInternalChannelDomainEntitySpeechInterface';
import type { StarrynightComServerInternalChannelDomainValueobjectChannelStatus } from './starrynightComServerInternalChannelDomainValueobjectChannelStatus';
import type { StarrynightComServerInternalChannelApplicationDtoCreateChannelTranslationDTO } from './starrynightComServerInternalChannelApplicationDtoCreateChannelTranslationDTO';

export interface StarrynightComServerInternalChannelApplicationDtoUpdateChannelDTO {
  host_interface?: StarrynightComServerInternalChannelDomainEntityHostInterface;
  preferred_language_code?: StarrynightComServerInternalSharedValueobjectLanguageCode;
  speech_interface?: StarrynightComServerInternalChannelDomainEntitySpeechInterface;
  status?: StarrynightComServerInternalChannelDomainValueobjectChannelStatus;
  translations?: StarrynightComServerInternalChannelApplicationDtoCreateChannelTranslationDTO[];
}
