/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { PgtypeTimestamptz } from './pgtypeTimestamptz';
import type { StarrynightComServerInternalChannelDomainEntityHostInterface } from './starrynightComServerInternalChannelDomainEntityHostInterface';
import type { StarrynightComServerInternalSharedValueobjectLanguageCode } from './starrynightComServerInternalSharedValueobjectLanguageCode';
import type { StarrynightComServerInternalChannelDomainEntitySpeechInterface } from './starrynightComServerInternalChannelDomainEntitySpeechInterface';
import type { StarrynightComServerInternalChannelDomainValueobjectChannelStatus } from './starrynightComServerInternalChannelDomainValueobjectChannelStatus';

export interface StarrynightComServerInternalChannelApplicationDtoReadChannelDTO {
  created_at?: PgtypeTimestamptz;
  description?: string;
  host_interface?: StarrynightComServerInternalChannelDomainEntityHostInterface;
  id?: number;
  name?: string;
  preferred_language_code?: StarrynightComServerInternalSharedValueobjectLanguageCode;
  speech_interface?: StarrynightComServerInternalChannelDomainEntitySpeechInterface;
  status?: StarrynightComServerInternalChannelDomainValueobjectChannelStatus;
}
