/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type StarrynightComServerInternalChannelDomainValueobjectChannelStatus = typeof StarrynightComServerInternalChannelDomainValueobjectChannelStatus[keyof typeof StarrynightComServerInternalChannelDomainValueobjectChannelStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarrynightComServerInternalChannelDomainValueobjectChannelStatus = {
  ChannelStatusIdle: 'idle',
  ChannelStatusActive: 'active',
  ChannelStatusInactive: 'inactive',
} as const;
