/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type StarrynightComServerInternalChannelDomainValueobjectHostType = typeof StarrynightComServerInternalChannelDomainValueobjectHostType[keyof typeof StarrynightComServerInternalChannelDomainValueobjectHostType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarrynightComServerInternalChannelDomainValueobjectHostType = {
  HostTypeSingleHost: 'single_host',
  HostTypeDoubleHost: 'double_host',
} as const;
