/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type StarrynightComServerInternalSharedValueobjectLanguageCode = typeof StarrynightComServerInternalSharedValueobjectLanguageCode[keyof typeof StarrynightComServerInternalSharedValueobjectLanguageCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarrynightComServerInternalSharedValueobjectLanguageCode = {
  LanguageCodeKorean: 'ko',
  LanguageCodeEnglish: 'en',
} as const;
