/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { StarrynightComServerInternalSharedValueobjectLanguageCode } from './starrynightComServerInternalSharedValueobjectLanguageCode';

export interface StarrynightComServerInternalChannelApplicationDtoCreateChannelTranslationDTO {
  description?: string;
  language_code?: StarrynightComServerInternalSharedValueobjectLanguageCode;
  name?: string;
}
