/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */

export type StarrynightComServerInternalChannelDomainValueobjectSpeechType = typeof StarrynightComServerInternalChannelDomainValueobjectSpeechType[keyof typeof StarrynightComServerInternalChannelDomainValueobjectSpeechType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StarrynightComServerInternalChannelDomainValueobjectSpeechType = {
  SpeechTypeText: 'text',
  SpeechTypeVoice: 'voice',
} as const;
