/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Starry Night API
 * Starry Night API
 * OpenAPI spec version: 1.0.0
 */
import type { StarrynightComServerInternalChannelDomainValueobjectSpeechType } from './starrynightComServerInternalChannelDomainValueobjectSpeechType';

export interface StarrynightComServerInternalChannelDomainEntitySpeechInterface {
  type?: StarrynightComServerInternalChannelDomainValueobjectSpeechType;
}
